### ISSUE TITLE
iOS - app is not available right now

### ISSUE THREAD

**Issue by janstehno** [janstehno/cotw-companion#26]
So as my apple developer account subscription ended, users will no longer be available to download and update the app on iOS devices. This will last as long as I will not pay for it again. As I am a student and the app did not pay for the account throughout the year it was active, I have no way of paying for it right now. Last available version was 1.8.3. I hope you understand and I am really sorry for this inconvenience.

**Comment by Calinque** [comment]
Olá! @janstehno ainda no temos o retorno do app para IOS ?

**Comment by janstehno** [comment]
> Olá! @janstehno ainda no temos o retorno do app para IOS ?

I am afraid not. Due to the same reasons, I cannot deploy the app for iOS devices for now. I am sorry for the inconvenience.

**Comment by janstehno** [comment]
With the release of the version 1.10.0 - Sundarpatan Update, the app is again available on the App Store.
