### ISSUE TITLE
Bear drink times not updated

### ISSUE THREAD

**Issue by DanMan136** [janstehno/cotw-companion#79]
Grizzly bear on Yukon Valley and black bears still show the old drink times of 2000-0000. New drink times are 0400-0800 for bears. Please update companion app. Thank you for continuing support of the app! Especially on iOS! Much appreciated.
-Daniel-

**Comment by janstehno** [comment]
Yeah this was problem on my side. Already fixed in the newest version. Try to check for update. Thank you.

**Comment by DanMan136** [comment]
Ahh shoulda done that first! Thank you again
