### ISSUE TITLE
Mejora de jugabilidad en ps4. 

### ISSUE THREAD

**Issue by 69zeth69** [janstehno/cotw-companion#82]
-Podrían poner el cambio rápido ennla tecla triangulo. 
-Borrar los atajos qie no se usen en ps4.
- Se queda trabado el joystick después de hacer un cambio de arma en ps4. 
- Recarga de balas en cuadrado.
- saltar hacia adelante.

**Comment by janstehno** [comment]
This does not contain anything about the app. I have no connection to the game. Closing and deleting.
