### ISSUE TITLE
A partir del nivel 37 ya no dan puntos

### ISSUE THREAD

**Issue by 69zeth69** [janstehno/cotw-companion#85]
A partir del nivel 37 ya no dan puntos, debería ser más fácil recibir puntos y llenar todas las habilidades y ventajas, para disfrutar del juego y de sus dlc.... No arruinen el juego hay muchos reclamos...

**Comment by janstehno** [comment]
This is a repository for a mobile app, not the game. For suggestions like these make sure to visit official Discord or send them a feedback ticket on the official site for the game. I have to connection to them so I can do nothing with this. As this is not relevant here, it will be closed and deleted.
