### ISSUE TITLE
No me da puntos de habilidad ni de ventaja

### ISSUE THREAD

**Issue by 69zeth69** [janstehno/cotw-companion#87]
Ya no me da puntos de nivel ni de ventajas a partir del nivel 37, debería ser más fácil conseguir los puntos y llenar por completo las cantabas y las habilidades, para disfrutar el juego y cazar en todos los mapas, a mi me gusta llenar habilidades y ventajas al completo para disfrutar el resto de mapas y objetivos primarios y secundarios.

**Comment by janstehno** [comment]
I have no influence on the game. The app is not affiliated, maintained, nor endored by the game developers at all.

The issues should be connected to the app only. As this one is not, it will be closed and deleted.
