### ISSUE TITLE
Trophy lodge & Catch book stats do not consider applied filter

### ISSUE THREAD

**Issue by Kapelutekkk** [janstehno/cotw-companion#88]
the application does not count the number of animals in the hunting lodge after setting filters. 

before the update I entered the name of the animal and after turning on the statistics I saw how many I have in the hunting lodge. Now I only see all species despite the filter setting.

**Comment by janstehno** [comment]
Oh, did not know. Hardly using stats. I will look into it. Thank you for spotting the issue.

**Comment by janstehno** [comment]
Fixed in 1.10.8
